### PR TITLE
cleaner code during group meeting

### PR DESCRIPTION
**Pull request by sandraskj**
please slaughter where you can and want @sbillinge @maak-sdu @J-Griffo

### CODE REVIEW

**Comment by sandraskj** [comment]
ping on this. @maak-sdu, @J-Griffo and @sbillinge, I would really appreciate your feedback on this.

**Review by sbillinge — COMMENTED** [review]
here is a slightly tweaked docstring, that is in the right format:
```
def create_tilt_dict(glazersystem): 
    """Constructs and initializes the Glazer tilt parameter dictionary

    Takes in the Glazer system ID for the user's chosen Glazer 
    system and returns dict of initial refinement values based 
	on global parameters ALPHA_I, BETA_I and GAMMA_I set by the 
	user.

    Parameters
    ----------
    glazersystem: integer
        the number of the Glazer system.

    Returns
    ----------
    tilt_values :  dict, 
       the values of the three tilts, alpha_i, beta_i and gamma_i
    """
```

make sure all variable names are lower case.

**Comment by maak-sdu** [comment]
> here is a slightly tweaked docstring, that is in the right format:
> 
> ```
> def create_tilt_dict(glazersystem): 
>     """Constructs and initializes the Glazer tilt parameter dictionary
> 
>     Takes in the Glazer system ID for the user's chosen Glazer 
>     system and returns dict of initial refinement values based 
> 	on global parameters ALPHA_I, BETA_I and GAMMA_I set by the 
> 	user.
> 
>     Parameters
>     ----------
>     glazersystem: integer
>         the number of the Glazer system.
> 
>     Returns
>     ----------
>     tilt_values :  dict, 
>        the values of the three tilts, alpha_i, beta_i and gamma_i
>     """
> ```
> 
> make sure all variable names are lower case.

I tried to browse various PEPs and the numpydoc. I didn't manage to find the convention for the tabs used before the 'Parameters'. If it follows a particular, I would much appreciate, if you would share. Thanks.

The same also goes for the comma after 'dict' in: 'tilt_values :  dict,'

**Comment by sbillinge** [comment]
I am not sure if that is a standard, but I normally indent by two spaces.
Some of the tabs were put in by GitHub so don't worry too much about those.

S

On Thu, May 12, 2022 at 8:54 AM Martin Aaskov Karlsen <
***@***.***> wrote:

> here is a slightly tweaked docstring, that is in the right format:
>
> def create_tilt_dict(glazersystem):
>     """Constructs and initializes the Glazer tilt parameter dictionary
>
>     Takes in the Glazer system ID for the user's chosen Glazer
>     system and returns dict of initial refinement values based
> 	on global parameters ALPHA_I, BETA_I and GAMMA_I set by the
> 	user.
>
>     Parameters
>     ----------
>     glazersystem: integer
>         the number of the Glazer system.
>
>     Returns
>     ----------
>     tilt_values :  dict,
>        the values of the three tilts, alpha_i, beta_i and gamma_i
>     """
>
> make sure all variable names are lower case.
>
> I tried to browse various PEPs and the numpydoc. I didn't manage to find
> the convention for the tabs used before the 'Parameters'. If it follows a
> particular, I would much appreciate, if you would share. Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandraskj_glazer-5Ffitting_pull_1-23issuecomment-2D1124602913&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=XST5Rm0FUaduIMMnyC9xV66hhZQxfWIMc5cQXr5mqdWL2C3IBbM83I-AFsxaj-xN&s=Uf0KBe4Ce6is8CV0d73sHbFbssbOre-q1dxVDPcmPi8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUMQAKQ4P5TWBCQPGZDVJSTL5ANCNFSM5VI35UJQ&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=XST5Rm0FUaduIMMnyC9xV66hhZQxfWIMc5cQXr5mqdWL2C3IBbM83I-AFsxaj-xN&s=uLPEJLttUVBpXBTjaoXsRIO-kgxFeHYpRd-q6D952i0&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Simon Billinge
Professor, Columbia University
Physicist, Brookhaven National Laboratory

**Comment by sbillinge** [comment]
a few more comments:
1) statements like this "

Takes in the Glazer system ID for the user's chosen Glazer
    system and returns dict of initial refinement values

are not normally needed.  This is evident from the function signature and
the parameters and returns sections.

2) In the case of your function you are using some global variables so this
explanation is actually needed.  However, a better code design would be to
not use global variables but to pass in those values.  It makes the code
more reusable and less "spaghetti" and easier to read. This function is
actually acting as an object constructor so another possible design would
be to define a class that contains the tilt set for a particular structure
and make this the constructor ("__init__").  I don't recommend it here
because it is a more major rewrite and not worth the effort probably.

3) I would make the code more readable by listing all the settings for the
different Glazer modes in a single list.  It takes more space, but less
developer brain-power to figure out what is going on.  In the notebook you
can put it in a different cell then the cell can be expanded or collapsed
to make the code as a whole more or less readable.

I didn't have time to go through all the code but I thought I would share
some general thoughts on what I saw in case they are helpful.

S

On Thu, May 12, 2022 at 9:01 AM Simon Billinge ***@***.***> wrote:

> I am not sure if that is a standard, but I normally indent by two spaces.
> Some of the tabs were put in by GitHub so don't worry too much about those.
>
> S
>
> On Thu, May 12, 2022 at 8:54 AM Martin Aaskov Karlsen <
> ***@***.***> wrote:
>
>> here is a slightly tweaked docstring, that is in the right format:
>>
>> def create_tilt_dict(glazersystem):
>>     """Constructs and initializes the Glazer tilt parameter dictionary
>>
>>     Takes in the Glazer system ID for the user's chosen Glazer
>>     system and returns dict of initial refinement values based
>> 	on global parameters ALPHA_I, BETA_I and GAMMA_I set by the
>> 	user.
>>
>>     Parameters
>>     ----------
>>     glazersystem: integer
>>         the number of the Glazer system.
>>
>>     Returns
>>     ----------
>>     tilt_values :  dict,
>>        the values of the three tilts, alpha_i, beta_i and gamma_i
>>     """
>>
>> make sure all variable names are lower case.
>>
>> I tried to browse various PEPs and the numpydoc. I didn't manage to find
>> the convention for the tabs used before the 'Parameters'. If it follows a
>> particular, I would much appreciate, if you would share. Thanks.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandraskj_glazer-5Ffitting_pull_1-23issuecomment-2D1124602913&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=XST5Rm0FUaduIMMnyC9xV66hhZQxfWIMc5cQXr5mqdWL2C3IBbM83I-AFsxaj-xN&s=Uf0KBe4Ce6is8CV0d73sHbFbssbOre-q1dxVDPcmPi8&e=>,
>> or unsubscribe
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUMQAKQ4P5TWBCQPGZDVJSTL5ANCNFSM5VI35UJQ&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=XST5Rm0FUaduIMMnyC9xV66hhZQxfWIMc5cQXr5mqdWL2C3IBbM83I-AFsxaj-xN&s=uLPEJLttUVBpXBTjaoXsRIO-kgxFeHYpRd-q6D952i0&e=>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>
>
> --
> Simon Billinge
> Professor, Columbia University
> Physicist, Brookhaven National Laboratory
>


-- 
Simon Billinge
Professor, Columbia University
Physicist, Brookhaven National Laboratory

**Comment by maak-sdu** [comment]
It's a minor detail but I think some of the `if` statements in the `def rotate_octahedron(octahedron, tilt_values)` cell can be turned into `elif` statements. I do realize that it won't change the output but maybe make the code a little cleaner?

Current:
```
if amp[key] > 0:
    if pattern_indicator[key] > 0:
        typ = 'IP'
    if pattern_indicator[key] < 0:
        typ = 'OOP'
        
    # set sign of rotation for the current octahedron
    if list(B) in rotation_pattern[key][typ]['clockwise']:
        sign[key] = +1
    if list(B) in rotation_pattern[key][typ]['anti-clockwise']:
        sign[key] = -1
    
if amp[key] == 0:
    sign[key] = 0
```
Suggested:
```
if amp[key] > 0:
    if pattern_indicator[key] > 0:
        typ = 'IP'
    elif pattern_indicator[key] < 0:
        typ = 'OOP'
        
    # set sign of rotation for the current octahedron
    if list(B) in rotation_pattern[key][typ]['clockwise']:
        sign[key] = +1
    elif list(B) in rotation_pattern[key][typ]['anti-clockwise']:
        sign[key] = -1
    
elif amp[key] == 0:
    sign[key] = 0
```
In the bottom of the same cell (second last comment in the cell), it says `# Combining all relative around all three axes displacements`. Combining all relative displacements, or?

**Comment by maak-sdu** [comment]
In the cell of the `plotresults()` function, the type is not stated for `resfithook` in the docstring.
```
def plotresults(recipe, resfithook, figname):
    """
    Creates plots of the fitted PDF and residual, displays them, and
    then writes them to disk as *.pdf files.

    Parameters
    ----------
    recipe :     The optimized Fit Recipe object containing the PDF data
                 we wish to plot
    resfithook:  
    figname :    string, the location and name of the figure file to create

    Returns
    ----------
    None
    """
```

**Comment by maak-sdu** [comment]
In the `makerecipe()` function, a hard coded value of `8` appears. I believe the value reflects the multiplicity of each atom (according to the .cif input). It would probably be great, if the value could 'read' from the cif input, instead of being hard coded. I guess the number (i.e. multiplicity) depends on the supercell provided in the cif? (2x2x2 in this particular case)

In the next code block, another hard coded value of `16` appears. The above suggestion also applies here.
```
    x1_index = X_index[0*8:8*1]
    x2_index = X_index[1*8:8*2]
    x3_index = X_index[2*8:8*3]
    
    # Create dict for indices and xyzpars of oxygen spacegroup params
    index_xyzpars_X_dict = {}
    for par in spacegroupparams_X.xyzpars:
        atom_index = int(par.name.split("_")[-1]) +16
        if not atom_index in index_xyzpars_X_dict.keys():
            index_xyzpars_X_dict[atom_index] = [par]
        elif atom_index in index_xyzpars_X_dict.keys():
            index_xyzpars_X_dict[atom_index].append(par)
```
Close to the bottom of the same cell, I guess two of the `if` statements can be turned into `elif`.
Current:
```
for par in spacegroupparams_X.latpars:
    if par.name == "a":
        recipe.constrain(par, "{}".format(a_con))
    if par.name == "b":
        recipe.constrain(par, "{}".format(b_con))
    if par.name == "c":
        recipe.constrain(par, "{}".format(c_con))
```
Suggested:
```
for par in spacegroupparams_X.latpars:
    if par.name == "a":
        recipe.constrain(par, "{}".format(a_con))
    elif par.name == "b":
        recipe.constrain(par, "{}".format(b_con))
    elif par.name == "c":
        recipe.constrain(par, "{}".format(c_con))
```

**Comment by maak-sdu** [comment]
I guess a docstring is needed for the `class ResidualFitHook()`?
```
class ResidualFitHook(FitHook):

    def __init__(self):
        super(ResidualFitHook, self).__init__()
        self.rws = []

    def reset(self, recipe):
        self.rws = []

    def postcall(self, recipe, chiv):
        recipe: FitRecipe
        fc: FitContribution = next(iter(recipe._contributions.values()))
        rw = np.sqrt(np.sum(np.power(chiv, 2)) / np.sum(np.power(fc.profile.y, 2)))
        self.rws.append(rw)
```

**Comment by maak-sdu** [comment]
In the `main()` cell, where output dirs are made, I would suggest to name folder for structures `stru` instead of `str`. Then the folder name reflects the file type just like `fit` and `res` folders. I guess it's okay to keep the `fig` name (instead `pdf`) to avoid confusion and the `var` name for the `.yaml` file.
```
strdir = "output/str"  # Contains refined structures
```

**Comment by maak-sdu** [comment]
I made may way through the code. I hope that at least some of the inputs above can be of just some value. Please let me know, if you need me to elaborate or similar.

**Comment by J-Griffo** [comment]
The code is very well documented.

My only main input not mentioned so far regards the try-except blocks in create_tilt_dict and create_Aconstraints. In both functions, some variables are generated and a statement is printed if this fails. The function then tries to return these variables. This means that the printed statement (telling you why the functioned failed) is followed immediately by a 'variable not found' Exception (which doesn't give new information).

If the function is going to return an Exception anyway, I would make the printed statement the Exception message. This doesn't change functionality at all but might make error messages a little more readable.

For example,
Current:
```
try:
          tilt_values = TILTS[GLAZERSYSTEM]
          print('Refinement will start with values {}. \nPositive values signify in-phase tilt, negative values signify out-of-phase tilt.\n'.format(list(tilt_values.values())))
except:
          print('Found no start values for the the Glazer tilt amplitudes (ALPHA_I, BETA_I and/or GAMMA_I)')
return tilt_value
```
Suggested:
```
try:
          tilt_values = TILTS[GLAZERSYSTEM]
          print('Refinement will start with values {}. \nPositive values signify in-phase tilt, negative values signify out-of-phase tilt.\n'.format(list(tilt_values.values())))
except:
          raise Exception('Found no start values for the the Glazer tilt amplitudes (ALPHA_I, BETA_I and/or GAMMA_I)')
return tilt_value
```

**Comment by J-Griffo** [comment]
Also, in terms of cleaning up the repo (which is very organized), the backend folder contains only an empty file

**Comment by sandraskj** [comment]
Thanks so much, everyone! I will implement the suggestions starting now :)

**Comment by sbillinge** [comment]
Riffing on Jack's comments, I don't think you should be wrapping this in a
try/except clause at all. This will only raise an exception if there is a
bug in your code and if there is a bug in your code you want it to crash so
you can fix the bug, so just let it crash. If you are worried that the user
hasn't specified an angle that they need I would handle that separately
which again makes the code much more readable (related to the idea that you
don't use global variables in your function)

S

**Comment by sandraskj** [comment]
> a few more comments: 1) statements like this " Takes in the Glazer system ID for the user's chosen Glazer system and returns dict of initial refinement values are not normally needed. This is evident from the function signature and the parameters and returns sections. 2) In the case of your function you are using some global variables so this explanation is actually needed. However, a better code design would be to not use global variables but to pass in those values. It makes the code more reusable and less "spaghetti" and easier to read. This function is actually acting as an object constructor so another possible design would be to define a class that contains the tilt set for a particular structure and make this the constructor ("__init__"). I don't recommend it here because it is a more major rewrite and not worth the effort probably. 3) I would make the code more readable by listing all the settings for the different Glazer modes in a single list. It takes more space, but less developer brain-power to figure out what is going on. In the notebook you can put it in a different cell then the cell can be expanded or collapsed to make the code as a whole more or less readable. I didn't have time to go through all the code but I thought I would share some general thoughts on what I saw in case they are helpful. S
> […](#)

@sbillinge  Can you expand on what you mean by " 3) I would make the code more readable by listing all the settings for the different Glazer modes in a single list. It takes more space, but less developer brain-power to figure out what is going on. In the notebook you can put it in a different cell then the cell can be expanded or collapsed to make the code as a whole more or less readable." Can you maybe write a truncated example?

**Comment by sandraskj** [comment]
> a few more comments: 1) statements like this " Takes in the Glazer system ID for the user's chosen Glazer system and returns dict of initial refinement values are not normally needed. This is evident from the function signature and the parameters and returns sections. 2) In the case of your function you are using some global variables so this explanation is actually needed. However, a better code design would be to not use global variables but to pass in those values. It makes the code more reusable and less "spaghetti" and easier to read. This function is actually acting as an object constructor so another possible design would be to define a class that contains the tilt set for a particular structure and make this the constructor ("__init__"). I don't recommend it here because it is a more major rewrite and not worth the effort probably. 3) I would make the code more readable by listing all the settings for the different Glazer modes in a single list. It takes more space, but less developer brain-power to figure out what is going on. In the notebook you can put it in a different cell then the cell can be expanded or collapsed to make the code as a whole more or less readable. I didn't have time to go through all the code but I thought I would share some general thoughts on what I saw in case they are helpful. S
> […](#)
> On Thu, May 12, 2022 at 9:01 AM Simon Billinge ***@***.***> wrote: I am not sure if that is a standard, but I normally indent by two spaces. Some of the tabs were put in by GitHub so don't worry too much about those. S On Thu, May 12, 2022 at 8:54 AM Martin Aaskov Karlsen < ***@***.***> wrote: > here is a slightly tweaked docstring, that is in the right format: > > def create_tilt_dict(glazersystem): > """Constructs and initializes the Glazer tilt parameter dictionary > > Takes in the Glazer system ID for the user's chosen Glazer > system and returns dict of initial refinement values based > on global parameters ALPHA_I, BETA_I and GAMMA_I set by the > user. > > Parameters > ---------- > glazersystem: integer > the number of the Glazer system. > > Returns > ---------- > tilt_values : dict, > the values of the three tilts, alpha_i, beta_i and gamma_i > """ > > make sure all variable names are lower case. > > I tried to browse various PEPs and the numpydoc. I didn't manage to find > the convention for the tabs used before the 'Parameters'. If it follows a > particular, I would much appreciate, if you would share. Thanks. > > — > Reply to this email directly, view it on GitHub > <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandraskj_glazer-5Ffitting_pull_1-23issuecomment-2D1124602913&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=XST5Rm0FUaduIMMnyC9xV66hhZQxfWIMc5cQXr5mqdWL2C3IBbM83I-AFsxaj-xN&s=Uf0KBe4Ce6is8CV0d73sHbFbssbOre-q1dxVDPcmPi8&e=>, > or unsubscribe > <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUMQAKQ4P5TWBCQPGZDVJSTL5ANCNFSM5VI35UJQ&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=XST5Rm0FUaduIMMnyC9xV66hhZQxfWIMc5cQXr5mqdWL2C3IBbM83I-AFsxaj-xN&s=uLPEJLttUVBpXBTjaoXsRIO-kgxFeHYpRd-q6D952i0&e=> > . > You are receiving this because you were mentioned.Message ID: > ***@***.***> > -- Simon Billinge Professor, Columbia University Physicist, Brookhaven National Laboratory
> -- Simon Billinge Professor, Columbia University Physicist, Brookhaven National Laboratory

Can you expand on what you mean by " 3) I would make the code more readable by listing all the settings for the different Glazer modes in a single list. It takes more space, but less developer brain-power to figure out what is going on. In the notebook you can put it in a different cell then the cell can be expanded or collapsed to make the code as a whole more or less readable." Can you maybe write a truncated example?

**Comment by sandraskj** [comment]
> I guess a docstring is needed for the `class ResidualFitHook()`?
> 
> ```
> class ResidualFitHook(FitHook):
> 
>     def __init__(self):
>         super(ResidualFitHook, self).__init__()
>         self.rws = []
> 
>     def reset(self, recipe):
>         self.rws = []
> 
>     def postcall(self, recipe, chiv):
>         recipe: FitRecipe
>         fc: FitContribution = next(iter(recipe._contributions.values()))
>         rw = np.sqrt(np.sum(np.power(chiv, 2)) / np.sum(np.power(fc.profile.y, 2)))
>         self.rws.append(rw)
> ```

I don't actually know how to.... @sbillinge help?

**Comment by sbillinge** [comment]
this is overloading the standard FitHook by defining and storing a new
agreement factor.  I am not 100% sure where and how it is used without
digging deeper.  Is this Songsheng code?  He may know.   I would guess that
the postcall method gets called maybe at the end of a fit (for example,
when it converges or sthg?) and it appends this new rw to the list of other
rws that are computed by the original FitHook.  You would then be able to
access this new value along with any other rw definitions in hte base-class
in your code.

On Fri, May 13, 2022 at 1:11 AM sandraskj ***@***.***> wrote:

> I guess a docstring is needed for the class ResidualFitHook()?
>
> class ResidualFitHook(FitHook):
>
>     def __init__(self):
>         super(ResidualFitHook, self).__init__()
>         self.rws = []
>
>     def reset(self, recipe):
>         self.rws = []
>
>     def postcall(self, recipe, chiv):
>         recipe: FitRecipe
>         fc: FitContribution = next(iter(recipe._contributions.values()))
>         rw = np.sqrt(np.sum(np.power(chiv, 2)) / np.sum(np.power(fc.profile.y, 2)))
>         self.rws.append(rw)
>
> I don't actually know how to.... @sbillinge
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbillinge&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=EXu6q_CDWN1i2zbuQV6wG4F2Sh8s3aXf6PxnNwVHkFQ&e=>
> help?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandraskj_glazer-5Ffitting_pull_1-23issuecomment-2D1125498835&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=NNjj8ZugvsYGSbT1t8LUWfnnw-e9MTo9Y8MMHvS74Os&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUPMX6PAZWZ7NHD6FEDVJWFZFANCNFSM5VI35UJQ&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=mpAZVW18Yu_N3sAa2-huIcNZnanqcErxbE7bfXJ6zKY&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Simon Billinge
Professor, Columbia University
Physicist, Brookhaven National Laboratory

**Comment by sandraskj** [comment]
> this is overloading the standard FitHook by defining and storing a new agreement factor. I am not 100% sure where and how it is used without digging deeper. Is this Songsheng code? He may know. I would guess that the postcall method gets called maybe at the end of a fit (for example, when it converges or sthg?) and it appends this new rw to the list of other rws that are computed by the original FitHook. You would then be able to access this new value along with any other rw definitions in hte base-class in your code.


Yes it is Songsheng's code and does what you are saying. I use it in the plotfunction to show Rw vs iteration, since I like seeing how the fit progresses. But it is also not necessary to include in this code. If I do include it, is it necessary to write a docstring for it though?

**Comment by sbillinge** [comment]
just include it with no docstring.  np

On Fri, May 13, 2022 at 3:36 PM sandraskj ***@***.***> wrote:

> this is overloading the standard FitHook by defining and storing a new
> agreement factor. I am not 100% sure where and how it is used without
> digging deeper. Is this Songsheng code? He may know. I would guess that the
> postcall method gets called maybe at the end of a fit (for example, when it
> converges or sthg?) and it appends this new rw to the list of other rws
> that are computed by the original FitHook. You would then be able to access
> this new value along with any other rw definitions in hte base-class in
> your code.
> … <#m_6412720622682767822_>
> On Fri, May 13, 2022 at 1:11 AM sandraskj *@*.*> wrote: I guess a
> docstring is needed for the class ResidualFitHook()? class
> ResidualFitHook(FitHook): def init(self): super(ResidualFitHook,
> self).init() self.rws = [] def reset(self, recipe): self.rws = [] def
> postcall(self, recipe, chiv): recipe: FitRecipe fc: FitContribution =
> next(iter(recipe._contributions.values())) rw =
> np.sqrt(np.sum(np.power(chiv, 2)) / np.sum(np.power(fc.profile.y, 2)))
> self.rws.append(rw) I don't actually know how to.... @sbillinge
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbillinge&d=DwMFaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=6JBqbHeuq5LZM2gkW-qjnTkoAhvZ23WNwecpvfStC-9rZHWfAKzxPLe5ZsQ2MZSI&s=MIHnKaMYB3g3RxL-9wAYS0uGDYwteSgH6S-4cWSWDGw&e=>
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbillinge&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=EXu6q_CDWN1i2zbuQV6wG4F2Sh8s3aXf6PxnNwVHkFQ&e=
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbillinge&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=EXu6q_CDWN1i2zbuQV6wG4F2Sh8s3aXf6PxnNwVHkFQ&e=>
> help? — Reply to this email directly, view it on GitHub
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandraskj_glazer-5Ffitting_pull_1-23issuecomment-2D1125498835&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=NNjj8ZugvsYGSbT1t8LUWfnnw-e9MTo9Y8MMHvS74Os&e=
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandraskj_glazer-5Ffitting_pull_1-23issuecomment-2D1125498835&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=NNjj8ZugvsYGSbT1t8LUWfnnw-e9MTo9Y8MMHvS74Os&e=>,
> or unsubscribe
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUPMX6PAZWZ7NHD6FEDVJWFZFANCNFSM5VI35UJQ&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=mpAZVW18Yu_N3sAa2-huIcNZnanqcErxbE7bfXJ6zKY&e=
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUPMX6PAZWZ7NHD6FEDVJWFZFANCNFSM5VI35UJQ&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=gVf_vSnhS3AYfc4sqx6Mx0fbp0_JDlCB-VDJPeBRf1uum7XwzjEqAbQazZvDhc0r&s=mpAZVW18Yu_N3sAa2-huIcNZnanqcErxbE7bfXJ6zKY&e=>
> . You are receiving this because you were mentioned.Message ID: @.*>
> -- Simon Billinge Professor, Columbia University Physicist, Brookhaven
> National Laboratory
>
> Yes it is Songsheng's code and does what you are saying. I use it in the
> plotfunction to show Rw vs iteration, since I like seeing how the fit
> progresses. But it is also not necessary to include in this code. If I do
> include it, is it necessary to write a docstring for it though?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sandraskj_glazer-5Ffitting_pull_1-23issuecomment-2D1126065110&d=DwMFaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=6JBqbHeuq5LZM2gkW-qjnTkoAhvZ23WNwecpvfStC-9rZHWfAKzxPLe5ZsQ2MZSI&s=DWbU_wHrhgDdzoeC3gAV1pIKfA2XkaQ1lHFI2a4XcE8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUKURN4LHTPCKYIF3R3VJZLE5ANCNFSM5VI35UJQ&d=DwMFaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=6JBqbHeuq5LZM2gkW-qjnTkoAhvZ23WNwecpvfStC-9rZHWfAKzxPLe5ZsQ2MZSI&s=nqsT4zgz-0NVjNzuOr8t7EJvmEk19Hw3ym4-c4n9pcg&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Simon Billinge
Professor, Columbia University
Physicist, Brookhaven National Laboratory

**Comment by sandraskj** [comment]
@maak-sdu @sbillinge @J-Griffo I have now implemented the following suggestions:
- renamed parameters to be lower caps + simplified and made the naming more readable in many cases
- made some input parameters into dictionaries (glazer tilts and a displacement parameters) and got rid of some hard-coded variable names by reading in the keys of these dictionaries. Therefore variables should be initialized correctly even if the user changes the naming of those parameters.
- cleaned up the folders
- renamed input files to make them more readable
- cleaned up redundant comments and code, added needed comments and explanations 
- cleaned up and formatted all docstrings to the best of my ability (left the docstring for the fitreshook out)
- got rid of most global parameters and take them in explicitly where needed (I also did this for the makerecipe function, which makes for a lot of local variables to take in, but at least it is clear what the function does now)
- cleaned up the folders
- renamed input files to make them more readable
- cleaned up redundant comments and code, added needed comments and explanations 
- prettied up the plots
- changed a bunch of "if"s to "elif"s
- got rid of the "try"
- left the hard-coding of the atom index numbers in the main, but added a comment explaining that it is highly dependent on the order of atoms in the model structure cif file.

The only thing I didn't address yet is this comment from @sbillinge, as I still need more clarifications:
> I would make the code more readable by listing all the settings for the different Glazer modes in a single list. It takes more space, but less developer brain-power to figure out what is going on. In the notebook you can put it in a different cell then the cell can be expanded or collapsed to make the code as a whole more or less readable.

**Comment by sbillinge** [comment]
It is just a formatting issue.
  Key1: value 1,
  Key 2: value 2,
Is easier to read than,
  Key1: value 1, key 2: value 2

S

**Pull request merged**
